import { spawn } from "node:child_process";
import { readFileSync } from "node:fs";
import { cp, mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import path from "node:path";
import { afterAll, beforeAll, describe, expect, it } from "vitest";
import { repoRoot } from "../testing/files.test-support.js";

/**
 * `lib/cli.js`, the entry-point shim, run as a real child process.
 *
 * The shim is generated by `scripts/build-lib.mjs` rather than compiled from a
 * source module, so nothing else in the test suite executes it. That gap is
 * where a defect lived: the shim used to call `process.exit(await main(...))`,
 * which terminates the process immediately and takes with it anything Node had
 * not yet flushed. Two things were lost, both reproduced before this test
 * existed:
 *
 * - The opt-in audit log recorded nothing. src/tools/reports.ts starts the
 *   append without awaiting it, so `process.exit()` killed the write: after
 *   five runs the log file existed and was 0 bytes.
 * - Output over about 1 MiB was cut off whenever stdout is a pipe, which is
 *   exactly how an agent captures it. Writing 2,000,001 bytes then exiting
 *   delivered 1,048,576 bytes with exit code 0 and no error.
 *
 * **What is real here and what is not.** The shim itself and `processStreams`
 * (src/cli/render.ts) are the committed, shipped files, copied byte for byte.
 * Only `cli/main.js` is replaced, with a stub that emits a payload or starts an
 * audit write the same way src/tools/reports.ts does. That substitution is what
 * makes the test possible at all without credentials or a network: every real
 * path that produces a megabyte of output or an audit line goes through
 * `runtime.client()` and a live Google request first.
 *
 * **Why the static assertion below is not redundant.** The old shim's
 * truncation is a race, not a certainty: measured over twenty runs it truncated
 * eighteen times and completed twice. A behavioural test alone would therefore
 * catch a regression most of the time but not every time, so the shim's text is
 * pinned as well. The behavioural tests prove the guarantee holds; the pin is
 * what fails deterministically if somebody puts `process.exit()` back.
 */

const PAYLOAD_BYTES = 2_000_001;

let workDir: string;
let shimPath: string;

/**
 * A copy of the committed `lib/` with only `cli/main.js` replaced. The stub
 * reads what to do from the environment, so one copy serves every case below.
 * `void logger.record(...)` is deliberate and is exactly what
 * src/tools/reports.ts does: a log line is not worth delaying an answer for,
 * which is precisely why the process must not be torn down before it lands.
 */
const STUB_MAIN = `export async function main(argv, env, streams) {
  if (env.SHIM_TEST_MODE === "stdout") {
    streams.out("x".repeat(Number(env.SHIM_TEST_BYTES)));
    return 0;
  }
  if (env.SHIM_TEST_MODE === "audit") {
    const { createAuditLogger } = await import("../privacy/audit.js");
    const logger = createAuditLogger({ path: env.SHIM_TEST_AUDIT_PATH });
    void logger.record({ tool: "report", propertyId: "123456789", rows: 1 });
    return 0;
  }
  return Number(env.SHIM_TEST_EXIT_CODE ?? "0");
}
`;

beforeAll(async () => {
  workDir = await mkdtemp(path.join(tmpdir(), "open-ga4-shim-"));
  await cp(path.join(repoRoot, "lib"), path.join(workDir, "lib"), { recursive: true });
  await writeFile(path.join(workDir, "lib/cli/main.js"), STUB_MAIN, "utf8");
  shimPath = path.join(workDir, "lib/cli.js");
});

afterAll(async () => {
  await rm(workDir, { recursive: true, force: true });
});

/** Runs the shim with stdout and stderr piped, the way an agent captures it. */
function runShim(env: Record<string, string>): Promise<{ code: number | null; stdout: Buffer }> {
  return new Promise((resolve, reject) => {
    const child = spawn(process.execPath, [shimPath], {
      env: { ...process.env, ...env },
      stdio: ["ignore", "pipe", "pipe"],
    });
    const chunks: Buffer[] = [];
    child.stdout.on("data", (chunk: Buffer) => chunks.push(chunk));
    child.stderr.resume();
    child.on("error", reject);
    child.on("close", (code) => resolve({ code, stdout: Buffer.concat(chunks) }));
  });
}

describe("lib/cli.js, the entry-point shim", () => {
  it("sets process.exitCode rather than calling process.exit", () => {
    const shim = readFileSync(path.join(repoRoot, "lib/cli.js"), "utf8");
    expect(shim).toContain("process.exitCode = await main(");
    expect(shim, "process.exit() discards pending stdout and pending file writes").not.toContain(
      "process.exit(",
    );

    // The committed shim is generated, so the generator has to agree with it or
    // the next `npm run build` silently reintroduces the defect.
    const generator = readFileSync(path.join(repoRoot, "scripts/build-lib.mjs"), "utf8");
    expect(generator).toContain("process.exitCode = await main(");
  });

  it("delivers output larger than a pipe buffer in full", async () => {
    const { code, stdout } = await runShim({
      SHIM_TEST_MODE: "stdout",
      SHIM_TEST_BYTES: String(PAYLOAD_BYTES),
    });
    expect(stdout.length).toBe(PAYLOAD_BYTES);
    expect(code).toBe(0);
  });

  it("lets an audit-log write that was started but not awaited reach the filesystem", async () => {
    const logPath = path.join(workDir, "audit.log");
    const { code } = await runShim({ SHIM_TEST_MODE: "audit", SHIM_TEST_AUDIT_PATH: logPath });
    expect(code).toBe(0);

    const entry = JSON.parse(await readFile(logPath, "utf8")) as Record<string, unknown>;
    expect(entry).toMatchObject({ tool: "report", property: "123456789", rows: 1 });
  });

  it("appends rather than truncating, so a second run keeps the first line", async () => {
    const logPath = path.join(workDir, "audit-twice.log");
    await runShim({ SHIM_TEST_MODE: "audit", SHIM_TEST_AUDIT_PATH: logPath });
    await runShim({ SHIM_TEST_MODE: "audit", SHIM_TEST_AUDIT_PATH: logPath });

    const lines = (await readFile(logPath, "utf8")).trim().split("\n");
    expect(lines).toHaveLength(2);
  });

  it("still reports main's exit code to the shell", async () => {
    // `process.exitCode` is a different mechanism from `process.exit()`, and
    // the exit code is a contract: SKILL.md tells the agent what each one
    // means, so a shim that flushed output but always exited 0 would be worse
    // than the defect it replaced.
    const { code } = await runShim({ SHIM_TEST_MODE: "none", SHIM_TEST_EXIT_CODE: "3" });
    expect(code).toBe(3);
  });
});
