function byMetric(metricName) {
    return [{ desc: true, metric: { metricName } }];
}
export const PRESETS = [
    {
        id: "overview",
        intent: "Headline numbers for a period: users, sessions, engagement, key events, revenue.",
        kind: "core",
        dimensions: [],
        metrics: [
            "activeUsers",
            "newUsers",
            "sessions",
            "engagedSessions",
            "engagementRate",
            "averageSessionDuration",
            "screenPageViews",
            "eventCount",
            "keyEvents",
            "totalRevenue",
        ],
        limit: 1,
    },
    {
        id: "daily_trend",
        intent: "Day-by-day users, sessions and key events, for spotting a trend or a spike.",
        kind: "core",
        dimensions: ["date"],
        metrics: ["activeUsers", "newUsers", "sessions", "engagedSessions", "keyEvents"],
        orderBys: [{ desc: false, dimension: { dimensionName: "date", orderType: "NUMERIC" } }],
        limit: 400,
    },
    {
        id: "top_pages",
        intent: "Most-viewed pages.",
        kind: "core",
        dimensions: ["pagePath"],
        metrics: ["screenPageViews", "activeUsers", "userEngagementDuration", "keyEvents"],
        orderBys: byMetric("screenPageViews"),
        limit: 25,
    },
    {
        id: "landing_pages",
        intent: "Pages where sessions start, with bounce and engagement.",
        kind: "core",
        dimensions: ["landingPage"],
        metrics: ["sessions", "activeUsers", "newUsers", "engagementRate", "bounceRate", "keyEvents"],
        orderBys: byMetric("sessions"),
        limit: 25,
    },
    {
        id: "traffic_sources",
        intent: "Which sources and mediums sessions came from.",
        kind: "core",
        dimensions: ["sessionSourceMedium"],
        metrics: ["sessions", "activeUsers", "engagedSessions", "engagementRate", "keyEvents", "totalRevenue"],
        orderBys: byMetric("sessions"),
        limit: 25,
    },
    {
        id: "channels",
        intent: "Traffic grouped into Google's default channels: Organic Search, Direct, Referral, and so on.",
        kind: "core",
        dimensions: ["sessionDefaultChannelGroup"],
        metrics: ["sessions", "activeUsers", "newUsers", "engagedSessions", "engagementRate", "keyEvents"],
        orderBys: byMetric("sessions"),
        limit: 20,
    },
    {
        id: "countries",
        intent: "Where visitors are, by country.",
        kind: "core",
        dimensions: ["country"],
        metrics: ["activeUsers", "sessions", "engagedSessions", "engagementRate", "keyEvents"],
        orderBys: byMetric("activeUsers"),
        limit: 50,
    },
    {
        id: "devices",
        intent: "Desktop, mobile and tablet split.",
        kind: "core",
        dimensions: ["deviceCategory"],
        metrics: ["activeUsers", "sessions", "engagementRate", "screenPageViews", "keyEvents"],
        orderBys: byMetric("activeUsers"),
        limit: 10,
    },
    {
        id: "browsers",
        intent: "Browser share.",
        kind: "core",
        dimensions: ["browser"],
        metrics: ["activeUsers", "sessions", "engagementRate", "bounceRate"],
        orderBys: byMetric("activeUsers"),
        limit: 20,
    },
    {
        id: "events",
        intent: "All events by volume.",
        kind: "core",
        dimensions: ["eventName"],
        metrics: ["eventCount", "activeUsers", "eventCountPerUser"],
        orderBys: byMetric("eventCount"),
        limit: 30,
    },
    {
        id: "key_events",
        intent: "Conversions. Google renamed these to key events; both words mean the same thing.",
        kind: "core",
        dimensions: ["eventName"],
        metrics: ["keyEvents", "activeUsers", "eventCount"],
        orderBys: byMetric("keyEvents"),
        limit: 30,
    },
    {
        id: "ecommerce",
        intent: "Product performance: views, cart adds, purchases and item revenue.",
        kind: "core",
        dimensions: ["itemName"],
        metrics: ["itemsViewed", "itemsAddedToCart", "itemsPurchased", "itemRevenue", "cartToViewRate"],
        orderBys: byMetric("itemRevenue"),
        limit: 25,
        note: "Empty unless the property sends ecommerce events.",
    },
    {
        id: "sales_summary",
        intent: "Transactions, revenue and purchasers, with no product breakdown.",
        kind: "core",
        dimensions: [],
        metrics: [
            "ecommercePurchases",
            "transactions",
            "purchaseRevenue",
            "totalRevenue",
            "averagePurchaseRevenue",
            "addToCarts",
            "checkouts",
            "totalPurchasers",
            "firstTimePurchasers",
        ],
        limit: 1,
    },
    {
        id: "new_vs_returning",
        intent: "How much traffic is new versus returning visitors.",
        kind: "core",
        dimensions: ["newVsReturning"],
        metrics: ["activeUsers", "sessions", "engagementRate", "averageSessionDuration", "keyEvents"],
        orderBys: byMetric("activeUsers"),
        limit: 5,
        note: "A '(not set)' row here is normal and is not an error.",
    },
    {
        id: "search_terms",
        intent: "What visitors typed into the site's own search box.",
        kind: "core",
        dimensions: ["searchTerm"],
        metrics: ["eventCount", "activeUsers", "keyEvents"],
        orderBys: byMetric("eventCount"),
        limit: 50,
        note: "On-site search only. These are not Google organic search queries; the GA4 API does not " +
            "expose those; Search Console does.",
    },
    {
        id: "realtime_now",
        intent: "Who is on the site right now, by country.",
        kind: "realtime",
        dimensions: ["country"],
        metrics: ["activeUsers", "screenPageViews"],
        orderBys: byMetric("activeUsers"),
        limit: 20,
    },
    {
        id: "realtime_pages",
        intent: "Which screens people are on right now.",
        kind: "realtime",
        dimensions: ["unifiedScreenName"],
        metrics: ["activeUsers", "screenPageViews"],
        orderBys: byMetric("activeUsers"),
        limit: 20,
    },
    {
        id: "realtime_events",
        intent: "Events firing right now.",
        kind: "realtime",
        dimensions: ["eventName"],
        metrics: ["eventCount", "activeUsers"],
        orderBys: byMetric("eventCount"),
        limit: 20,
    },
];
export function findPreset(id) {
    return PRESETS.find((preset) => preset.id === id);
}
